abbr -a g       'git'
abbr -a gd      'git diff'
abbr -a gi      'git init'
abbr -a gs      'clear -x ; git status'
abbr -a gss     'clear -x ; git status -s'
abbr -a ga      'git add'
abbr -a gaa     'git add .'
abbr -a gc      'git commit'
abbr -a gcm     'git commit -m'
abbr -a gch     'git checkout'
abbr -a gb      'git branch'
abbr -a gre     'git remote'
abbr -a gcnf    'git config'
abbr -a gcnfg   'git config'
abbr -a gf      'git fetch'
abbr -a gp      'git pull'
abbr -a grm     'git rm'
